name: v1-server-test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  sched-job-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: |
          cd v1/server
          npm i
      - name: Test
        run: |
          npm test